language: python

python:
  - 3.6

cache:
  - pip

install:
  - pip install -qU pip setuptools
  - pip install -q pytest==3.6 pytest-cov coverage
  - pip install -q chainer networkx chainer_computational_cost
  - pip install -q chainercv
  - pip install -q -e .

script:
  - pytest -vv tests
