FROM chainer/chainer:v7.0.0a1-python3

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG C.UTF-8
ENV LANGUAGE en_US

RUN pip3 install \
    networkx \
    scipy \
    chainer_computational_cost
# TODO chainerpruner